# Site's URL. Please include trailing "/".
base_url = "https://harper.rocks/"
title = "harper.rocks"
description = "Personal Blog !"

compile_sass = true
build_search_index = true
generate_feeds = true
minify_html = false

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
# highlight_theme = "base16-ocean-dark"

exclude_paginated_pages_in_sitemap = "all"